// AUTO-GENERATED from Dungeon_Seeds.md by build-tables.ts. Do not edit by hand.
import type { PairedTable, RoomType } from "../types/rollTypes.ts";

export const purpose: PairedTable = {
    columns: ["Original Use", "Built By"],
    rows: [
        ["Ancestral Rites", "A Fallen Hero"],
        ["Arcane Library", "A Fanatical Cult"],
        ["Astral Trading Hub", "A Forgotten Empire"],
        ["Bestial Creations", "A Long-Dead Poet"],
        ["Breeding Grounds", "A Militant Order"],
        ["Burial Site", "A Renowned Alchemist"],
        ["Celestial Observations", "A Royal Dynasty"],
        ["Covert Experiments", "A Secret Society"],
        ["Forbidden Trysts", "A Tyrannical Ruler"],
        ["Forge for a Great Weapon", "A Warrior Tribe"],
        ["Hideout", "A Wealthy Recluse"],
        ["Impenetrable Vault", "Desperate Rebels"],
        ["Invasion of Dreams", "Heretical Alchemists"],
        ["Isolated Refuge", "Heretical Monks"],
        ["Military Outpost", "Immoral Sorcerers"],
        ["Observatory", "Inverted Astrologers"],
        ["Pilgrimage Site", "Mob Families"],
        ["Protection of Rare Artifacts", "Opulent Merchants"],
        ["Secret Meeting Place", "Pilgrims to a Dead God"],
        ["Treasure Horde", "Rogue Scholars"],
    ],
};

export const construction: PairedTable = {
    columns: ["Entrance", "Composition"],
    rows: [
        ["A Creature's Lair", "Bone"],
        ["A Dream", "Coral"],
        ["A Massive Tree", "Crystal"],
        ["A Well", "Earth"],
        ["An Enormous Grave", "Ethereal Fabric"],
        ["Behind a Waterfall", "Flesh"],
        ["Between Menhirs", "Floating Platforms"],
        ["Cave", "Fungi"],
        ["Center of a Maze", "Glass"],
        ["Cliff door", "Ice"],
        ["Hollow Statue", "Living Plants"],
        ["Illusory Wall", "Marble"],
        ["Mine Shaft", "Metal"],
        ["Sinking Sand", "Obsidian"],
        ["Skyward Beam of Light", "Petrified Wood"],
        ["Starlight Path", "Sand"],
        ["Through a Painting", "Shadow Material"],
        ["Under a Bridge", "Stone"],
        ["Underwater Tunnel", "Webs"],
        ["Veil of Mist", "Wood"],
    ],
};

export const ruination: PairedTable = {
    columns: ["Condition", "Cause"],
    rows: [
        ["Corpse", "Alchemical Accident"],
        ["Crumbling", "Ancient Curse"],
        ["Cursed", "Cataclysmic Flood"],
        ["Desecrated", "Civil War"],
        ["Devoured", "Competing Rituals"],
        ["Displaced", "Consumed by a Beast"],
        ["Divided", "Disease"],
        ["Frozen", "Hedonism"],
        ["Haunted", "Invasion"],
        ["Infested", "Long-Term Abandonment"],
        ["Overgrown", "Magic Gone Awry"],
        ["Overpopulated", "Magical Seal"],
        ["Petrified", "Natural Disaster"],
        ["Plundered", "Natural Erosion"],
        ["Poisoned", "Obfuscation"],
        ["Scorched", "Overrun with Monsters"],
        ["Shrouded in Mist", "Sudden Change in Climate"],
        ["Submerged", "Teleported to Another Realm"],
        ["Unending", "Turned to Stone"],
        ["Warped", "Unresolved Spirits"],
    ],
};

export const traits: PairedTable = {
    columns: ["Virtues", "Vices"],
    rows: [
        ["Compassionate", "Absent-Minded"],
        ["Courageous", "Aloof"],
        ["Creative", "Critical"],
        ["Deductive", "Cynical"],
        ["Honest", "Greedy"],
        ["Incisive", "Impulsive"],
        ["Incorruptible", "Inflexible"],
        ["Individualistic", "Naive"],
        ["Loyal", "Obstinate"],
        ["Methodical", "Passive"],
        ["Polite", "Pedantic"],
        ["Practical", "Perfectionist"],
        ["Resilient", "Sarcastic"],
        ["Scholarly", "Selfish"],
        ["Self-Sufficient", "Skeptical"],
        ["Solid", "Stubborn"],
        ["Studious", "Superficial"],
        ["Suave", "Unfocused"],
        ["Unwavering", "Unimaginative"],
        ["Witty", "Vain"],
    ],
};

export const agendas: PairedTable = {
    columns: ["Goal", "Obstacle"],
    rows: [
        ["Ascension", "Conflict"],
        ["Creation", "Corruption"],
        ["Destruction", "Cost"],
        ["Dominion", "Danger"],
        ["Enlightenment", "Decay"],
        ["Exploration", "Discord"],
        ["Growth", "Division"],
        ["Innovation", "Dogma"],
        ["Justice", "Exposure"],
        ["Knowledge", "Factionalism"],
        ["Liberation", "Fear"],
        ["Peace", "Ignorance"],
        ["Power", "Incompetence"],
        ["Preservation", "Injustice"],
        ["Protection", "Isolation"],
        ["Redemption", "Opposition"],
        ["Revenge", "Sacrifice"],
        ["Survival", "Stagnation"],
        ["Transformation", "Tradition"],
        ["Wealth", "Weakness"],
    ],
};

export const monster: PairedTable = {
    columns: ["Group", "Activity"],
    rows: [
        ["Avian", "Building"],
        ["Beast", "Devouring"],
        ["Behemoth", "Dying"],
        ["Construct", "Fighting"],
        ["Demon", "Growing"],
        ["Extraplanar", "Haunting"],
        ["Fey", "Hiding"],
        ["Giant", "Killing"],
        ["Goblinoid", "Mating"],
        ["Humanoid", "Mourning"],
        ["Hybrid", "Patrolling"],
        ["Incorporeal", "Praying"],
        ["Insectoid", "Protecting"],
        ["Lizard", "Recuperating"],
        ["Magical", "Scheming"],
        ["Mythical", "Sleeping"],
        ["Plant", "Stalking"],
        ["Shape Shifter", "Torturing"],
        ["Undead", "Training"],
        ["Unusual", "Trapped"],
    ],
};

export const lore: PairedTable = {
    columns: ["Room Type", "Clue"],
    rows: [
        ["Armory", "Decay"],
        ["Barracks", "Decor"],
        ["Bath", "Draft"],
        ["Cistern", "Echoes"],
        ["Court", "Footprints"],
        ["Crypt", "Leavings"],
        ["Den", "Light"],
        ["Dining Hall", "Markings"],
        ["Guard Post", "Moisture"],
        ["Infirmary", "Noise"],
        ["Kitchen", "Paraphernalia"],
        ["Latrine", "Residue"],
        ["Library", "Scurrying"],
        ["Shrine", "Signs"],
        ["Smith", "Smell"],
        ["Stable", "Stains"],
        ["Storage", "Tapping"],
        ["Study", "Temperature"],
        ["Vault", "Vibrations"],
        ["Workshop", "Writing"],
    ],
};

export const special: PairedTable = {
    columns: ["Special", "Feature"],
    rows: [
        ["Books", "Ages"],
        ["Bridge", "Alarms"],
        ["Contraption", "Animates"],
        ["Creature", "Attracts"],
        ["Door", "Charges"],
        ["Flames", "Closes"],
        ["Furniture", "Falls"],
        ["Hole", "Glows"],
        ["Liquid", "Grows"],
        ["Mirror", "Illusion"],
        ["Mural", "Levitates"],
        ["Pool", "Locks"],
        ["Shadows", "Opens"],
        ["Smoke", "Reflects"],
        ["Statue", "Repels"],
        ["Surface", "Reveals"],
        ["Treasure", "Shifts"],
        ["Voices", "Silences"],
        ["Wheel", "Teleport"],
        ["Writing", "Transforms"],
    ],
};

export const trap: PairedTable = {
    columns: ["Trap", "Trigger"],
    rows: [
        ["Ages", "Activating"],
        ["Burns", "Breaking"],
        ["Captures", "Crossing"],
        ["Carries", "Disturbing"],
        ["Confuses", "Entering"],
        ["Crushes", "Extinguishing"],
        ["Curses", "Focusing"],
        ["Cuts", "Interacting"],
        ["Deafens", "Lighting"],
        ["Drops", "Moving"],
        ["Drowns", "Opening"],
        ["Freezes", "Pulling"],
        ["Glues", "Pushing"],
        ["Hypnotizes", "Reading"],
        ["Impales", "Speaking"],
        ["Infects", "Stepping"],
        ["Lifts", "Taking"],
        ["Poisons", "Talking"],
        ["Shocks", "Touching"],
        ["Shoots", "Tripping"],
    ],
};

// Weight = faces on the die; total weight is the die size
export const defaultRoomTypes: RoomType[] = [
    { name: "Monster", weight: 1, table: monster },
    { name: "Lore", weight: 2, table: lore },
    { name: "Special", weight: 1, table: special },
    { name: "Trap", weight: 2, table: trap },
];